DROP TABLE IF EXISTS Sleeps;
DROP TABLE IF EXISTS CalendarEvents;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
	userID INT(11) NOT NULL AUTO_INCREMENT,
    forename VARCHAR(25) NOT NULL,
    surname VARCHAR(25) NOT NULL,
    username VARCHAR(25) NOT NULL,
    userPassword VARCHAR(25) NOT NULL,
	PRIMARY KEY (userID)
);

CREATE TABLE Sleeps (
	sleepID INT(11) NOT NULL AUTO_INCREMENT,
	sleepStart DATETIME NOT NULL,
	sleepEnd DATETIME NOT NULL,
	userID INT(11) NOT NULL,
	PRIMARY KEY (sleepID),
	CONSTRAINT FK_UserSleeps FOREIGN KEY (userID)
	REFERENCES Users(userID)
);

CREATE TABLE CalendarEvents (
	eventID INT(11) NOT NULL AUTO_INCREMENT,
	eventDate DATETIME NOT NULL,
	eventDescription VARCHAR(255),
	userID INT(11) NOT NULL,
	PRIMARY KEY (eventID),
	CONSTRAINT FK_UserEvents FOREIGN KEY (userID)
	REFERENCES Users(userID)
);